### ISSUE TITLE
Arrows on powerflow plot

### ISSUE THREAD

**Issue by noahrhodes** [WISPO-POP/PowerPlots.jl#82]
Should be able to support arrows on powerplot for line power flow based on this example:

https://www.queryverse.org/VegaLite.jl/v2.1/examples/examples_table_based_plots/#Wind-Vector-Map-1

**Comment by bryanluu** [comment]
Which direction is `pf` and `pt` with respect to `xcoord_1` and `xcoord_2`?

**Comment by bryanluu** [comment]
> Which direction is `pf` and `pt` with respect to `xcoord_1` and `xcoord_2`?

Based on some quick experimentation, it looks like `pf` is the power going to the bus `f_bus`, and `pt` is the power going to the bus `t_bus`. Can you confirm @noahrhodes?

**Comment by noahrhodes** [comment]
size based on power makes sense, but I think the arrows could be a different color (maybe black by default) because they are hard to see. I also think it makes sense to turn off the legend  by default.  All of these can be a part of plot attributes though, and let people change the values as they see fit. 

Also, I'm not sure about the arrows being on by default.  Often the entries for pf and pt are missing, unless someone has solved a power-flow on the network and updated the the entries.  Does the plot crash if pt and pf are missing?

**Comment by noahrhodes** [comment]
Based on the PowerModels [docs](https://lanl-ansi.github.io/PowerModels.jl/stable/network-data/#Working-with-Matpower-Data-Files), pf is the power going out of the f_bus and into the line, while pt is the power going out of the t_bus and into the line.  I think this is the opposite of what you stated.

**Comment by bryanluu** [comment]
## Tasks to do to finish up
- [ ] Add new (boolean) plot attribute `show_flow` that toggles whether arrows are shown
- [ ] Add documentation for new plot attributes
  - [ ] `docs/src/parameters.md`
- [ ] Add an example for arrows
  - [ ] `docs/src/examples/basic_examples.md`

**Comment by bryanluu** [comment]
@noahrhodes I forget, did you want the flow arrows to be on or off by default?

**Comment by noahrhodes** [comment]
On by default

**Comment by bryanluu** [comment]
@noahrhodes  how do I run the examples again?

**Comment by noahrhodes** [comment]
you can run the make.jl file in the docs folder
